problem/urls.py
from django.conf.urls import url
from problem.views import artifact1
from problem.views import artifact2
from problem.views import artifact3
from problem.views import artifact4
from problem.views import artifact5
from problem.views import artifact6
from problem.views import artifact7
from problem.views import artifact8
from problem.views import artifact9
from problem.views import artifact10
from problem.views import artifact11
from problem.views import artifact12
from problem.views import artifact13
from problem.views import artifact14
from problem.views import anti1, anti2, anti3, case1, case2, case3, case4
from problem.views import problem_view
from problem.views import problem_write
from problem.views import problem_write_done
from problem.views import problem_answercheck
from problem.views import scenario_answercheck
from problem.views import problem_download

urlpatterns = [
	url(r'^forensic/1/', artifact1, name='artifact1'),
	url(r'^forensic/2/', artifact2, name='artifact2'),
	url(r'^forensic/3/', artifact3, name='artifact3'),
	url(r'^forensic/4/', artifact4, name='artifact4'),
	url(r'^forensic/5/', artifact5, name='artifact5'),
	url(r'^forensic/6/', artifact6, name='artifact6'),
	url(r'^forensic/7/', artifact7, name='artifact7'),
	url(r'^forensic/8/', artifact8, name='artifact8'),
	url(r'^forensic/9/', artifact9, name='artifact9'),
	url(r'^forensic/10/', artifact10, name='artifact10'),
	url(r'^forensic/11/', artifact11, name='artifact11'),
	url(r'^forensic/12/', artifact12, name='artifact12'),
	url(r'^forensic/13/', artifact13, name='artifact13'),
	url(r'^forensic/14/', artifact14, name='artifact14'),
	url(r'^antiforensic/1/', anti1, name='anti1'),
	url(r'^antiforensic/2/', anti2, name='anti2'),
	url(r'^antiforensic/3/', anti3, name='anti3'),
	url(r'^scenario/1/', case1, name='case1'),
	url(r'^scenario/2/', case2, name='case2'),
	url(r'^scenario/3/', case3, name='case3'),
	url(r'^scenario/4/', case4, name='case4'),
	url(r'^view/$', problem_view, name='problem_view'),
	url(r'^write/$', problem_write, name='problem_write'),
	url(r'^write_done/$', problem_write_done, name='problem_write_done'),
	url(r'^answer_check/$', problem_answercheck, name='problem_answercheck'),
	url(r'^scenario/answer_check/$', scenario_answercheck, name='scenario_answercheck'),
	url(r'^download/$', problem_download, name='problem_download'),
]

problem/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class Problem(models.Model):
	num = models.AutoField(primary_key=True)
	artifact = models.PositiveSmallIntegerField(null=True)
	title = models.CharField(max_length=50, blank=True)
	author = models.ForeignKey('auth.User')
	created_date = models.DateField(blank=True)
	level = models.PositiveSmallIntegerField(null=True)
	right_answer = models.CharField(max_length=100, null=True)
	submits = models.IntegerField(blank=True, null=True)
	corrects = models.IntegerField(blank=True, null=True)
	tags = models.CharField(max_length=200, null=True, blank=True)
	importance = models.PositiveSmallIntegerField(null=True)
	difficulty = models.PositiveSmallIntegerField(null=True)
	score = models.IntegerField(null=True)
	downfile = models.FileField(null=True, blank=True)
	content = models.TextField(null=True, blank=True)
	solve_user = models.CharField(max_length=200, null=True, blank=True)

	def __unicode__(self):
		return self.title

class Answerlog(models.Model):
	num = models.AutoField(primary_key=True)
	submitter = models.ForeignKey('auth.User')
	problem_num = models.IntegerField(null=True)
	problem_title = models.CharField(max_length=50, null=True)
	submit_answer = models.CharField(max_length=10000, null=True)
	submit_date = models.DateTimeField(auto_now_add=True)

	def __unicode__(self):
		return self.submit_answer

class Scenario(models.Model):
	snum = models.IntegerField(null=True)
	answer_num = models.IntegerField(null=True)
	score = models.IntegerField(null=True)
	answer1 = models.CharField(max_length=100, null=True, blank=True)
	answer2 = models.CharField(max_length=100, null=True, blank=True)
	answer3 = models.CharField(max_length=100, null=True, blank=True)
	answer4 = models.CharField(max_length=100, null=True, blank=True)
	answer5 = models.CharField(max_length=100, null=True, blank=True)
	answer6 = models.CharField(max_length=100, null=True, blank=True)
        answer7 = models.CharField(max_length=100, null=True, blank=True)
        answer8 = models.CharField(max_length=100, null=True, blank=True)
        answer9 = models.CharField(max_length=100, null=True, blank=True)
        answer10 = models.CharField(max_length=100, null=True, blank=True)
        answer11 = models.CharField(max_length=100, null=True, blank=True)
        answer12 = models.CharField(max_length=100, null=True, blank=True)
        answer13 = models.CharField(max_length=100, null=True, blank=True)
        answer14 = models.CharField(max_length=100, null=True, blank=True)
        answer15 = models.CharField(max_length=100, null=True, blank=True)

problem/templates/case4/list.html
{% extends 'problem_menu.html' %}

{% block problem_content %}
<script type="text/javascript">
	$(document).ready(function() {
		$('#problem-menu > li:eq(2)').toggleClass("active");
		$('#problem-menu > li:eq(2) > ul').css("display", "block");
		$('#problem-menu > li:eq(2) > ul > li:eq(3)').toggleClass("active");

		$('#problem-menu > li:eq(0)').hover(function () {
			$(this).addClass("active");
			$(this).find("ul:first").show(); 
		}, function () {
			$(this).removeClass("active");
			$(this).find("ul:first").hide(); 
		});

		$('#problem-menu > li:eq(1)').hover(function () {
			$(this).addClass("active");
			$(this).find("ul:first").show();
		}, function () {
			$(this).removeClass("active");
			$(this).find("ul:first").hide();
		});
	});
</script>
<div class="case4-content col-md-10">
	<div style="overflow: auto;">
		<h2 class="question-title">바이러스</h2>
		<h5 class="question-date">2016년 11월 24일</h5>
	</div>
	<hr>
	<span>Download: </span>
	<a href="https://drive.google.com/open?id=0BxNYyukorb8qWGlISlVXUUhMbUE" target="_blank">HDD Dump File</a>
	<hr>
	<p class="scenario-content">평소에 은행거래를 할 일이 많아, 인터넷 뱅킹을 자주 이용하던 라팀장은 평소처럼 은행 업무를 보던 도중 일일 이체 한도를 초과하였다는 메시지를 확인하였고, 이를 이상하게 여겨, 은행 이체기록을 확인 해 본 결과 라팀장이 이체하지 않은 돈들이 매우 많이 빠져나가 있는 것을 확인 할 수 있었다. 이를 이상하게 여긴 라팀장은 자신의 PC가 해킹을 당했다고 생각하고 당신에게 수사를 의뢰하였다..</p>

	<p class="scenario-content">당신은 신고를 받고 “DumpIt”도구를 이용하여 메모리 덤프를 생성하라고 안내 해 준 후 라팀장의 집에 방문하여 PC의 HDD덤프를 수집하였다.</p>

  	<p class="scenario-content">당신은 사이버 수사대의 수사관으로써 해당 사건이 해킹임을 증명하여, 라팀장이 적법한 보상을 받을 수 있도록, 범인을 검거하기 위한 증거를 확보 하여야 한다. 해당 PC를 분석하시오.</p>
	<ol>
		<li>라 팀장이 주로 이용하는 주 거래 은행은?(한글명을 그대로 영문입력 ex. 한글 -> gksrmf)</li>
		<li>라 팀장의 컴퓨터에서 가장 최근 실행된 파일은 무엇인가? (name-xxxx.pf)</li>
		<li>라 팀장이 계좌이체를 하여 송금을 하여야 하는 계좌의 목록은 몇 개인가?(숫자만 입력)</li>
		<li>라 팀장이 해킹을 당하게 되는 원인이 된 웹사이트의 최초 접근시간을 적으시오.(UTC+9 기준, 인증형식 : link_YYYY-MM-DD_hh-mm-ss)</li>
		<li>라 팀장의 계좌를 탈취하기 위해 이용한 범인이 이용한 IP Address는?</li>
		<!--<li>라 팀장의 메일계정 id/pw는 어떻게 되는가?(인증형식 : id_password)</li>-->
		<li>라 팀장의 PC를 해킹한 악성 봇넷이 저장된 경로는?(파일명을 포함하며, 경로의 구분은 "/"로 한다.)</li>
		<li>해커가 라팀장의 PC에 접근하기 위하여 사용한 PASS Key는 무었인가?</li>
		<li>라 팀장의 PC가 해킹을 당한 당시의 라 팀장의 PC 부팅 날짜와 시각은 언제인가?(재부팅은 무시한다.)(YYYY-MM-DD_hh-mm-ss 형식)</li>
		<li>라 팀장의 PC에 설치되어 있던 악성 프로그램의 Process name과 Mutex 값을 입력하시오(Proccess name_Mutex Value)</li>
		<!--<li>해커가 라 팀장의 PC 쉘에서 사용한 명령어는 몇개인가?(숫자만 입력)</li>-->
		<li>해커가 라 팀장의 PC를 조종하기 위하여 이용한 IP Address, Port는?(IP_PORT)</li>
	</ol>

	        <p class = "scenario-content"><strong>위 문제 항목을 풀이하신 후에  문제 풀이 보고서(분석보고서)를 Community의 시나리오 보고서  게시판에 올려주시면 전문가 분들이 해당 보고서에 대한 피드백을 적어드립니다. 조금 더 빠른 피드백을 원하시면 cres.webadm@gmail.com로 분석보고서를 보내주시면 됩니다.</strong></p>

	<form id="input_answer" class="form-horizontal" method="POST" action="{% url 'scenario_answercheck' %}?snum=4100">{% csrf_token %}
                {% load scenario_problem_num %}
                <div class="form-group">
                        <label for="id_answer1" class="col-md-2 control-label">No.1</label>
                        <div class="col-md-8">
                                <input type="text" id="id_answer1" class="form-control" name="answer1" {% for right in right_problem %}{% ifequal right|scenario_problem_num 1 %}value="Already Solved" disabled{% endifequal %} {% endfor %} placeholder="Answer" required>
                        </div>
                </div>
                <div class="form-group">
                        <label for="id_answer2" class="col-md-2 control-label">No.2</label>
                        <div class="col-md-8">
                                <input type="text" id="id_answer2" class="form-control" name="answer2" {% for right in right_problem %}{% ifequal right|scenario_problem_num 2 %}value="Already Solved" disabled{% endifequal %} {% endfor %} placeholder="Answer" required>
                        </div>
                </div>
                <div class="form-group">
                        <label for="id_answer3" class="col-md-2 control-label">No.3</label>
                        <div class="col-md-8">
                                <input type="text" id="id_answer3" class="form-control" name="answer3" {% for right in right_problem %}{% ifequal right|scenario_problem_num 3 %}value="Already Solved" disabled{% endifequal %} {% endfor %} placeholder="Answer" required>
                        </div> 
                </div>
		<div class="form-group">
                        <label for="id_answer4" class="col-md-2 control-label">No.4</label>
                        <div class="col-md-8">
                                <input type="text" id="id_answer4" class="form-control" name="answer4" {% for right in right_problem %}{% ifequal right|scenario_problem_num 4 %}value="Already Solved" disabled{% endifequal %} {% endfor %} placeholder="Answer" required>
                        </div>
                </div>
		<div class="form-group">
                        <label for="id_answer5" class="col-md-2 control-label">No.5</label>
                        <div class="col-md-8">
                                <input type="text" id="id_answer5" class="form-control" name="answer5" {% for right in right_problem %}{% ifequal right|scenario_problem_num 5 %}value="Already Solved" disabled{% endifequal %} {% endfor %} placeholder="Answer" required>
                        </div>
                </div>
		<div class="form-group">
                        <label for="id_answer6" class="col-md-2 control-label">No.6</label>
                        <div class="col-md-8">
                                <input type="text" id="id_answer6" class="form-control" name="answer6" {% for right in right_problem %}{% ifequal right|scenario_problem_num 6 %}value="Already Solved" disabled{% endifequal %} {% endfor %} placeholder="Answer" required>
                        </div>
                </div>
		<div class="form-group">
                        <label for="id_answer7" class="col-md-2 control-label">No.7</label>
                        <div class="col-md-8">
                                <input type="text" id="id_answer7" class="form-control" name="answer7" {% for right in right_problem %}{% ifequal right|scenario_problem_num 7 %}value="Already Solved" disabled{% endifequal %} {% endfor %} placeholder="Answer" required>
                        </div>
                </div>
		<div class="form-group">
                        <label for="id_answer8" class="col-md-2 control-label">No.8</label>
                        <div class="col-md-8">
                                <input type="text" id="id_answer8" class="form-control" name="answer8" {% for right in right_problem %}{% ifequal right|scenario_problem_num 8 %}value="Already Solved" disabled{% endifequal %} {% endfor %} placeholder="Answer" required>
                        </div>
                </div>
		<div class="form-group">
                        <label for="id_answer9" class="col-md-2 control-label">No.9</label>
                        <div class="col-md-8">
                                <input type="text" id="id_answer9" class="form-control" name="answer9" {% for right in right_problem %}{% ifequal right|scenario_problem_num 9 %}value="Already Solved" disabled{% endifequal %} {% endfor %} placeholder="Answer" required>
                        </div>
                </div>
		<div class="form-group">
                        <label for="id_answer10" class="col-md-2 control-label">No.10</label>
                        <div class="col-md-8">
                                <input type="text" id="id_answer10" class="form-control" name="answer10" {% for right in right_problem %}{% ifequal right|scenario_problem_num 10 %}value="Already Solved" disabled{% endifequal %} {% endfor %} placeholder="Answer" required>
                        </div>
			<div class="col-md-2">
                                <input type="submit" id="id_submit" class="btn btn-default" value="Submit" {% if state %}disabled{% endif %}>
                        </div>
                </div>
        </form>

	<div class="col-md-12" style="text-align: center;">
                <h4 style="display: inline-block">바이러스 설문조사 :</h4>
                <a href="https://goo.gl/zHE5TZ" target="_blank">https://goo.gl/zHE5TZ</a>
        </div>
</div>
{% endblock problem_content %}