problem/urls.py
from django.conf.urls import url
from problem.views import artifact1
from problem.views import artifact2
from problem.views import artifact3
from problem.views import artifact4
from problem.views import artifact5
from problem.views import artifact6
from problem.views import artifact7
from problem.views import artifact8
from problem.views import artifact9
from problem.views import artifact10
from problem.views import artifact11
from problem.views import artifact12
from problem.views import artifact13
from problem.views import artifact14
from problem.views import anti1, anti2, anti3, case1, case2, case3, case4
from problem.views import problem_view
from problem.views import problem_write
from problem.views import problem_write_done
from problem.views import problem_answercheck
from problem.views import scenario_answercheck
from problem.views import problem_download

urlpatterns = [
	url(r'^forensic/1/', artifact1, name='artifact1'),
	url(r'^forensic/2/', artifact2, name='artifact2'),
	url(r'^forensic/3/', artifact3, name='artifact3'),
	url(r'^forensic/4/', artifact4, name='artifact4'),
	url(r'^forensic/5/', artifact5, name='artifact5'),
	url(r'^forensic/6/', artifact6, name='artifact6'),
	url(r'^forensic/7/', artifact7, name='artifact7'),
	url(r'^forensic/8/', artifact8, name='artifact8'),
	url(r'^forensic/9/', artifact9, name='artifact9'),
	url(r'^forensic/10/', artifact10, name='artifact10'),
	url(r'^forensic/11/', artifact11, name='artifact11'),
	url(r'^forensic/12/', artifact12, name='artifact12'),
	url(r'^forensic/13/', artifact13, name='artifact13'),
	url(r'^forensic/14/', artifact14, name='artifact14'),
	url(r'^antiforensic/1/', anti1, name='anti1'),
	url(r'^antiforensic/2/', anti2, name='anti2'),
	url(r'^antiforensic/3/', anti3, name='anti3'),
	url(r'^scenario/1/', case1, name='case1'),
	url(r'^scenario/2/', case2, name='case2'),
	url(r'^scenario/3/', case3, name='case3'),
	url(r'^scenario/4/', case4, name='case4'),
	url(r'^view/$', problem_view, name='problem_view'),
	url(r'^write/$', problem_write, name='problem_write'),
	url(r'^write_done/$', problem_write_done, name='problem_write_done'),
	url(r'^answer_check/$', problem_answercheck, name='problem_answercheck'),
	url(r'^scenario/answer_check/$', scenario_answercheck, name='scenario_answercheck'),
	url(r'^download/$', problem_download, name='problem_download'),
]

problem/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class Problem(models.Model):
	num = models.AutoField(primary_key=True)
	artifact = models.PositiveSmallIntegerField(null=True)
	title = models.CharField(max_length=50, blank=True)
	author = models.ForeignKey('auth.User')
	created_date = models.DateField(blank=True)
	level = models.PositiveSmallIntegerField(null=True)
	right_answer = models.CharField(max_length=100, null=True)
	submits = models.IntegerField(blank=True, null=True)
	corrects = models.IntegerField(blank=True, null=True)
	tags = models.CharField(max_length=200, null=True, blank=True)
	importance = models.PositiveSmallIntegerField(null=True)
	difficulty = models.PositiveSmallIntegerField(null=True)
	score = models.IntegerField(null=True)
	downfile = models.FileField(null=True, blank=True)
	content = models.TextField(null=True, blank=True)
	solve_user = models.CharField(max_length=200, null=True, blank=True)

	def __unicode__(self):
		return self.title

class Answerlog(models.Model):
	num = models.AutoField(primary_key=True)
	submitter = models.ForeignKey('auth.User')
	problem_num = models.IntegerField(null=True)
	problem_title = models.CharField(max_length=50, null=True)
	submit_answer = models.CharField(max_length=10000, null=True)
	submit_date = models.DateTimeField(auto_now_add=True)

	def __unicode__(self):
		return self.submit_answer

class Scenario(models.Model):
	snum = models.IntegerField(null=True)
	answer_num = models.IntegerField(null=True)
	score = models.IntegerField(null=True)
	answer1 = models.CharField(max_length=100, null=True, blank=True)
	answer2 = models.CharField(max_length=100, null=True, blank=True)
	answer3 = models.CharField(max_length=100, null=True, blank=True)
	answer4 = models.CharField(max_length=100, null=True, blank=True)
	answer5 = models.CharField(max_length=100, null=True, blank=True)
	answer6 = models.CharField(max_length=100, null=True, blank=True)
        answer7 = models.CharField(max_length=100, null=True, blank=True)
        answer8 = models.CharField(max_length=100, null=True, blank=True)
        answer9 = models.CharField(max_length=100, null=True, blank=True)
        answer10 = models.CharField(max_length=100, null=True, blank=True)
        answer11 = models.CharField(max_length=100, null=True, blank=True)
        answer12 = models.CharField(max_length=100, null=True, blank=True)
        answer13 = models.CharField(max_length=100, null=True, blank=True)
        answer14 = models.CharField(max_length=100, null=True, blank=True)
        answer15 = models.CharField(max_length=100, null=True, blank=True)

problem/templates/_all_problems_bak.html
{% extends 'base.html' %}

{% block content %}
<script type="text/javascript">
	$(document).ready(function() {
		$('nav .active').toggleClass("active");
		$('nav ul li:eq(3)').toggleClass("active");
	});
</script>
<div class="container content">
	<div class="menu col-md-2">
		<ul id="problem-menu" class="nav nav-pills nav-stacked">
			<li class="active"><a href="#artifact1">Artifact 1</a></li>
			<li><a href="#artifact2">Artifact 2</a></li>
			<li><a href="#artifact3">Artifact 3</a></li>
			<li><a href="#artifact4">Artifact 4</a></li>
			<li><a href="#artifact5">Artifact 5</a></li>
		</ul>
		<script type="text/javascript">
			var pmenu = $('#problem-menu a');
			for (var i = 0; i < pmenu.length; i++){
				$('#problem-menu a:eq('+i+')').click(function(e) {
					e.preventDefault();
					$(this).tab('show');
				});
			};
		</script>
	</div>
	<div class="problem-content col-md-10">
		<div class="tab-content">
			<div class="tab-pane fade in active" id="artifact1">
				<h1>Artifact 1</h1>
				<table class="table table-bordered">
					<thead>
						<tr>
							<td>#</td>
							<td>Problem</td>
							<td>Level</td>
							<td>stats</td>
						</tr>
					</thead>
					<div class="hidden">{{ counter.setzero }}</div>
					{% for problem in problems %}
						{% ifequal problem.artifact 1 %}
						<tr>
							<td class="problem_num col-md-1">{{ counter.count|add:"1" }}</td>
							<td class="col-md-8"><a href="#">{{ problem.title }}</a></td>
							<td>level{{ problem.level }}</td>
							<td></td>
							<div class="hidden">{{ counter.increment }}</div>
						</tr>
						{% endifequal %}
					{% endfor %}
				</table>
			</div>
			<div class="tab-pane fade" id="artifact2">
				<h1>Artifact 2</h1>
				<table class="table table-bordered">
					<thead>
						<tr>
							<td>#</td>
							<td>Problem</td>
							<td>Level</td>
							<td>stats</td>
						</tr>
					</thead>
					<div class="hidden">{{ counter.setzero }}</div>
					{% for problem in problems %}
						{% ifequal problem.artifact 2 %}
						<tr>
							<td class="problem_num col-md-1">{{ counter.count|add:"1" }}</td>
							<td class="col-md-8"><a href="#">{{ problem.title }}</a></td>
							<td>level{{ problem.level }}</td>
							<td></td>
							<div class="hidden">{{ counter.increment }}</div>
						</tr>
						{% endifequal %}
					{% endfor %}
				</table>
			</div>
			<div class="tab-pane fade" id="artifact3">
				<h1>Artifact 3</h1>
				<table class="table table-bordered">
					<thead>
						<tr>
							<td>#</td>
							<td>Problem</td>
							<td>Level</td>
							<td>stats</td>
						</tr>
					</thead>
					<div class="hidden">{{ counter.setzero }}</div>
					{% for problem in problems %}
						{% ifequal problem.artifact 3 %}
						<tr>
							<td class="problem_num col-md-1">{{ counter.count|add:"1" }}</td>
							<td class="col-md-8"><a href="#">{{ problem.title }}</a></td>
							<td>level{{ problem.level }}</td>
							<td></td>
							<div class="hidden">{{ counter.increment }}</div>
						</tr>
						{% endifequal %}
					{% endfor %}
				</table>
			</div>
			<div class="tab-pane fade" id="artifact4">
				<h1>Artifact 4</h1>
				<table class="table table-bordered">
					<thead>
						<tr>
							<td>#</td>
							<td>Problem</td>
							<td>Level</td>
							<td>stats</td>
						</tr>
					</thead>
					<div class="hidden">{{ counter.setzero }}</div>
					{% for problem in problems %}
						{% ifequal problem.artifact 4 %}
						<tr>
							<td class="problem_num col-md-1">{{ counter.count|add:"1" }}</td>
							<td class="col-md-8"><a href="#">{{ problem.title }}</a></td>
							<td>level{{ problem.level }}</td>
							<td></td>
							<div class="hidden">{{ counter.increment }}</div>
						</tr>
						{% endifequal %}
					{% endfor %}
				</table>
			</div>
			<div class="tab-pane fade" id="artifact5">
				<h1>Artifact 5</h1>
				<table class="table table-bordered">
					<thead>
						<tr>
							<td>#</td>
							<td>Problem</td>
							<td>Level</td>
							<td>stats</td>
						</tr>
					</thead>
					<div class="hidden">{{ counter.setzero }}</div>
					{% for problem in problems %}
						{% ifequal problem.artifact 5 %}
						<tr>
							<td class="problem_num col-md-1">{{ counter.count|add:"1" }}</td>
							<td class="col-md-8"><a href="#">{{ problem.title }}</a></td>
							<td>level{{ problem.level }}</td>
							<td></td>
							<div class="hidden">{{ counter.increment }}</div>
						</tr>
						{% endifequal %}
					{% endfor %}
				</table>
			</div>
		</div>
	</div>
</div>
{% if test.user.is_superuser %}
	<div style="overflow: auto;">
		<input class="btn btn-info pull-right" type="button" value="Add Problem" onclick="location.href='/admin/problem/problem/add'"></input>
	</div>
{% endif %}

{% endblock content %}

problem/templates/_recommend_problem.html
{% load problem_stats %}
<div class="container problem center col-md-12 col-sm-12 col-xs-12">
		<div class="problem-title">
			<span>Recommended Problems</span>
		</div>
		{% if test.user.is_active %}
			{% if test.user.is_staff %}
				<table class="table table-bordered">
					<thead>
						<tr>
							<td>#</td>
							<td>Problem</td>
							<td>Artifact</td>
							<td>Pass/Submits</td>
						</tr>
					</thead>
					<tbody>
					{% for problem in problems %}
						<tr>
							<td class="problem_num col-md-1">{{ counter.count }}</td>
							<td class="col-md-8"><a href="{% url 'problem_view' %}?pnum={{ problem.num }}">{{ problem.title }}</a></td>
							<td class="problem_center">
							{% if problem.artifact == 1 %}
							Prefetch
							{% elif problem.artifact == 2 %}
							Event Log
							{% elif problem.artifact == 3 %}
							LNK
							{% elif problem.artifact == 4 %}
							Shimcache
							{% elif problem.artifact == 5 %}
							Memory Dump
							{% elif problem.artifact == 6 %}
							Network
							{% elif problem.artifact == 7 %}
							Thumbnail
							{% elif problem.artifact == 8 %}
							VSS
							{% elif problem.artifact == 9 %}
							Web browser
							{% elif problem.artifact == 10 %}
							WER
							{% elif problem.artifact == 11 %}
							MFT
							{% elif problem.artifact == 12 %}
							File system
							{% elif problem.artifact == 13 %}
							Registry
							{% elif problem.artifact == 14 %}
							File Magic
							{% elif problem.artifact == 15 %}
							Steganography
							{% elif problem.artifact == 16 %}
							Hidden File
							{% elif problem.artifact == 17 %}
							File Delete
							{% endif %}
							</td>
							<td class="problem_center">{{ problem.corrects|getstats:problem.submits }} ({{ problem.corrects }}/{{ problem.submits }})</td>
						</tr>
						{{ counter.increment|default_if_none:"" }}
					{% endfor %}
					</tbody>
				</table>
			{% endif %}
			{% for profile in profiles %}
				{% if test.user.id == profile.user_id and not test.user.is_staff%}
					<table class="table table-bordered">
					<thead>
						<tr>
							<td>#</td>
							<td>Problem</td>
							<td>Artifact</td>
							<td>Pass/Submits</td>
						</tr>
					</thead>
					<tbody>
					{% for problem in problems %}
						{% ifequal profile.level problem.level %}
							<tr>
								<td class="problem_num col-md-1">{{ counter.count }}</td>
								<td class="col-md-8"><a href="{% url 'problem_view' %}?pnum={{ problem.num }}">{{ problem.title }}</a></td>
								<td class="problem_center">
								{% if problem.artifact == 1 %}
								Prefetch
								{% elif problem.artifact == 2 %}
								Event Log
								{% elif problem.artifact == 3 %}
								LNK
								{% elif problem.artifact == 4 %}
								Shimcache
								{% elif problem.artifact == 5 %}
								Memory Dump
								{% elif problem.artifact == 6 %}
								Network
								{% elif problem.artifact == 7 %}
								Thumbnail
								{% elif problem.artifact == 8 %}
								VSS
								{% elif problem.artifact == 9 %}
								Web browser
								{% elif problem.artifact == 10 %}
								WER
								{% elif problem.artifact == 11 %}
								MFT
								{% elif problem.artifact == 12 %}
								File system
								{% elif problem.artifact == 13 %}
								Registry
								{% elif problem.artifact == 14 %}
								File Magic
								{% elif problem.artifact == 15 %}
								Steganography
								{% elif problem.artifact == 16 %}
								Hidden File
								{% elif problem.artifact == 17 %}
								File Delete
								{% endif %}
								</td>
								<td class="problem_center">{{ problem.corrects|getstats:problem.submits }} ({{ problem.corrects }}/{{ problem.submits }})</td>
							</tr>
							{{ counter.increment|default_if_none:"" }}
						{% endifequal %}
					{% endfor %}
					</tbody>
					</table>
				{% endif %}
			{% endfor %}
		{% else %}
			<h2>&nbsp;&nbsp;Login Please</h2>
		{% endif %}
</div>

problem/templates/problem_answercheck.html
<html>
	<head>
		{% load staticfiles %}
		<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" />
		<script type="text/javascript" src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
		<script src="{% static 'js/bootstrap.min.js' %}"></script>
	</head>
	<body>
		{% if state %}
		<div class="modal fade">
			<div class="modal-dialog">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" id="hexit" class="close" data-dismiss="modal">×</button>
						<h4 class="modal-title">Correct!!</h4>
					</div>
					<div class="modal-body" style="text-align: center;">
						정답입니다.
					</div>
					<div class="modal-footer">
						<button type="button" id="exit" class="btn btn-default" data-dismiss="modal">닫기</button>
					</div>
				</div>
			</div>
		</div>
		<script type="text/javascript">
			$('div.modal').modal({
				backdrop: 'static',
				keyboard: false
			});
			$('#exit').focus();

			$('#hexit').click(function() {
				location.href = "{% url 'problem_view' %}?pnum={{ problem_num }}";
			});
			$('#exit').click(function() {
				location.href = "{% url 'problem_view' %}?pnum={{ problem_num }}";
			});
		</script>
		{% else %}
		<div class="modal fade">
			<div class="modal-dialog">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" id="hexit" class="close" data-dismiss="modal">×</button>
						<h4 class="modal-title">Wrong!!</h4>
					</div>
					<div class="modal-body" style="text-align: center;">
						오답입니다.
					</div>
					<div class="modal-footer">
						<button type="button" id="exit" class="btn btn-default" data-dismiss="modal">닫기</button>
					</div>
				</div>
			</div>
		</div>
		<script type="text/javascript">
			$('div.modal').modal({
				backdrop: 'static',
				keyboard: false
			});
			$('#exit').focus();

			$('#hexit').click(function() {
				location.href = "{% url 'problem_view' %}?pnum={{ problem_num }}";
			});
			$('#exit').click(function() {
				location.href = "{% url 'problem_view' %}?pnum={{ problem_num }}";
			});
		</script>
		{% endif %}
	</body>
</html>

problem/templates/problem_menu.html
{% extends 'base.html' %}

{% block content %}
<script type="text/javascript">
	$(document).ready(function() {
		$('nav ul li:eq(3)').toggleClass("active");
	{% if request.user.is_staff %}	
		$('#addbutton').click(function() {
			$(location).attr("href", "{% url 'problem_write' %}");
		});
	{% endif %}
	});
</script>
<div class="col-md-12">
<div class="menu col-md-2">
	<ul id="problem-menu" class="nav nav-pills nav-stacked">
		<li><a href="{% url 'artifact1' %}?orderby=title">Artifact Analysis</a>
			<ul class="nav nav-pills nav-stacked submenu">
				<li><a href="{% url 'artifact1' %}?orderby=title">Prefetch</a></li>
				<li><a href="{% url 'artifact2' %}?orderby=title">Event Log</a></li>
				<li><a href="{% url 'artifact3' %}?orderby=title">LNK</a></li>
				<li><a href="{% url 'artifact4' %}?orderby=title">Shimcache</a></li>
				<li><a href="{% url 'artifact5' %}?orderby=title">Memory Dump</a></li>
				<li><a href="{% url 'artifact6' %}?orderby=title">Network</a></li>
				<li><a href="{% url 'artifact7' %}?orderby=title">Thumbnail</a></li>
				<li><a href="{% url 'artifact8' %}?orderby=title">VSS</a></li>
				<li><a href="{% url 'artifact9' %}?orderby=title">Web Browser History</a></li>
				<li><a href="{% url 'artifact10' %}?orderby=title">WER & Crash Dump</a></li>
				<li><a href="{% url 'artifact11' %}?orderby=title">MFT</a></li>
				<li><a href="{% url 'artifact12' %}?orderby=title">File System</a></li>
				<li><a href="{% url 'artifact13' %}?orderby=title">Registry</a></li>
				<li><a href="{% url 'artifact14' %}?orderby=title">File Magic</a></li>
			</ul>
		</li>
		<li><a href="{% url 'anti1' %}">Anti-Forensic</a>
			<ul class="nav nav-pills nav-stacked submenu">
				<li><a href="{% url 'anti1' %}">Steganography</a></li>
				<li><a href="{% url 'anti2' %}">Hidden File</a></li>
				<li><a href="{% url 'anti3' %}">File Delete</a></li>
			</ul>
		</li>
		<li><a href="{% url 'case1' %}">Scenario</a>
			<ul class="nav nav-pills nav-stacked submenu">
				<li><a href="{% url 'case1' %}">랜섬웨어</a></li>
				<li><a href="{% url 'case2' %}">정보 유출</a></li>
				<li><a href="{% url 'case3' %}">네트워크 공격</a></li>
				<li><a href="{% url 'case4' %}">바이러스</a></li>
			</ul>
		</li>
	</ul>
</div>

{% block problem_content %}
{% endblock problem_content %}

{% if request.user.is_staff %}
	<div class="addproblem">
		<input id="addbutton" class="btn btn-info pull-right" type="button" value="Add Problem">
	</div>
{% endif %}
</div>
{% endblock content %}

problem/templates/problem_solved.html
<html>
	<head>
		{% load staticfiles %}
		<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" />
		<script type="text/javascript" src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
		<script src="{% static 'js/bootstrap.min.js' %}"></script>
	</head>
	<body>
		<div class="modal fade">
			<div class="modal-dialog">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" id="hexit" class="close" data-dismiss="modal">×</button>
						<h4 class="modal-title">Already Solved!!</h4>
					</div>
					<div class="modal-body" style="text-align: center;">
						이미 푼 문제입니다.
					</div>
					<div class="modal-footer">
						<button type="button" id="exit" class="btn btn-default" data-dismiss="modal">닫기</button>
					</div>
				</div>
			</div>
		</div>
		<script type="text/javascript">
			$('div.modal').modal({
				backdrop: 'static',
				keyboard: false
			});
			$('#exit').focus();

			$('#hexit').click(function() {
				{% if problem_num == 0 %}
					{% if scenario_num == 1 %}
						location.href = "{% url 'case1' %}";
					{% elif scenario_num == 2 %}
						location.href = "{% url 'case2' %}";
					{% elif scenario_num == 3 %}
						location.href = "{% url 'case3' %}";
					{% elif scenario_num == 4 %}
						location.href = "{% url 'case4' %}";
					{% endif %}
				{% else %}
					location.href = "{% url 'problem_view' %}?pnum={{ problem_num }}";
				{% endif %}
			});
			$('#exit').click(function() {
				{% if problem_num == 0 %}
					{% if scenario_num == 1 %}
						location.href = "{% url 'case1' %}";
					{% elif scenario_num == 2 %}
						location.href = "{% url 'case2' %}";
					{% elif scenario_num == 3 %}
						location.href = "{% url 'case3' %}";
					{% elif scenario_num == 4 %}
						location.href = "{% url 'case4' %}";
					{% endif %}
				{% else %}
					location.href = "{% url 'problem_view' %}?pnum={{ problem_num }}";
				{% endif %}
			});
		</script>
	</body>
</html>

problem/templates/problem_write.html
{% extends 'problem_menu.html' %}

{% block problem_content %}
<script type="text/javascript">
	{% if not request.user.is_staff %}
		alert('You don\'t have writing permission!!');
		$(location).attr("href", "{% url 'home' %}");
	{% endif %}
	$(document).ready(function() {
		$('#problem-menu > li:eq(0)').hover(function () {
			$(this).addClass("active");
			$(this).find("ul:first").show(); 
		}, function () {
			$(this).removeClass("active");
			$(this).find("ul:first").hide(); 
		});

		$('#problem-menu > li:eq(1)').hover(function () {
			$(this).addClass("active");
			$(this).find("ul:first").show(); 
		}, function () {
			$(this).removeClass("active");
			$(this).find("ul:first").hide(); 
		});

		$('#problem-menu > li:eq(2)').hover(function () {
			$(this).addClass("active");
			$(this).find("ul:first").show();
		}, function () {
			$(this).removeClass("active");
			$(this).find("ul:first").hide();
		});

		$('#addbutton').addClass("hidden");
		$('#id_submit').click(function() {
			var form = $('#write_problem');

			if(!$('input[name=title]').val()) {
				alert('Input title.');
				$('input[name=title]').focus();
				return;
			}

			if(!$('input[name=level]').val()) {
				alert('Input level.');
				$('input[name=level]').focus();
				return;
			}

			if(!$('input[name=score]').val()) {
				alert('Input score.');
				$('input[name=score]').focus();
				return;
			}

			if(!$('input[name=tags]').val()) {
				alert('Input tags.');
				$('input[name=tags]').focus();
				return;
			}

			if(!$('input[name=right_answer]').val()) {
				alert('Input right answer.');
				$('input[name=right_answer]').focus();
				return;
			}

			if(!$('textarea[name=content]').val()) {
				alert('Input content.');
				$('textarea[name=content]').focus();
				return;
			}

			form.submit();
		});

		$('#id_reset').click(function() {
			$('select[name=artifact] option:eq(0)').prop("selected", true);
			$('input[name=title]').val("");
			$('input[name=level]').val("");
			$('input[name=score]').val("");
			$('input[name=tags]').val("");
			$('select[name=importance] option:eq(0)').prop("selected", true);
			$('select[name=difficulty] option:eq(0)').prop("selected", true);
			$('input[name=right_answer]').val("");
			$('textarea[name=content]').val("");
		});
	});	
</script>
<div class="problem-content col-md-10">
	<form id="write_problem" class="form-horizontal" method="POST" action="{% url 'problem_write_done' %}" enctype="multipart/form-data">{% csrf_token %}
		<div class="form-group">
			<label for="artifact" class="col-md-2 control-label">Artifact</label>
			<div class="col-md-10">
				<select name="artifact" class="form-control">
					<optgroup label="Artifact">
						<option value="1">Prefetch</option>
						<option value="2">Event Log</option>
						<option value="3">LNK</option>
						<option value="4">Shimcache</option>
						<option value="5">Memory Dump</option>
						<option value="6">Network</option>
						<option value="7">Thumbnail</option>
						<option value="8">VSS</option>
						<option value="9">Web Browser History</option>
						<option value="10">WER & Crash Dump</option>
						<option value="11">MFT</option>
						<option value="12">Fils System</option>
						<option value="13">Registry</option>
						<option value="14">File Magic</option>
					</optgroup>
					<optgroup label="Anti-Forensic">
						<option value="15">Steganography</option>
						<option value="16">Hidden File</option>
						<option value="17">File Delete</option>
					</optgroup>
				</select>
			</div>
		</div>
		<div class="form-group">
			<label for="id_title" class="col-md-2 control-label">Title</label>
			<div class="col-md-10">
				<input type="text" id="id_title" class="form-control" name="title" maxlength="50" placeholder="Title">
			</div>
		</div>
		<div class="form-group">
			<label for="id_author" class="col-md-2 control-label">Author</label>
			<div class="col-md-10">
				<input type="text" id="id_author" class="form-control" name="author" value="{{ request.user.username }}" disabled>
			</div>
		</div>
		<div class="form-group">
			<label for="id_level" class="col-md-2 control-label">Level</label>
			<div class="col-md-4">
				<input type="text" id="id_level" class="form-control" name="level" placeholder="Level">
			</div>
			<label for="id_score" class="col-md-2 control-label">Score</label>
			<div class="col-md-4">
				<input type="text" id="id_score" class="form-control" name="score" placeholder="Score">
			</div>
		</div>
		<div class="form-group">
			<label for="id_tags" class="col-md-2 control-label">Tags</label>
			<div class="col-md-10">
				<input type="text" id="id_tags" class="form-control" name="tags" placeholder="Tags">
			</div>
		</div>
		<div class="form-group">
			<label for="id_importance" class="col-md-2 control-label">Importance</label>
			<div class="col-md-4">
				<select name="importance" class="form-control">
					<option value="2">High</option>
					<option value="1">Middle</option>
					<option value="0">Low</option>
				</select>
			</div>
			<label for="id_difficulty" class="col-md-2 control-label">Difficulty</label>
			<div class="col-md-4">
				<select name="difficulty" class="form-control">
					<option value="2">High</option>
					<option value="1">Middle</option>
					<option value="0">Low</option>
				</select>
			</div>
		</div>
		<div class="form-group">
			<label for="id_right_answer" class="col-md-2 control-label">Right Answer</label>
			<div class="col-md-10">
				<input type="text" id="id_right_answer" class="form-control" name="right_answer" placeholder="Right Answer">
			</div>
		</div>
		<div class="form-group">
			<label for="id_file" class="col-md-2 control-label">Upload File</label>
			<div class="col-md-10">
				<input type="file" id="id_file" class="form-control" name="uploadfile">
			</div>
		</div>
		<div class="form-group">
			<label for="id_content" class="col-md-2 control-label">Content</label>
			<div class="col-md-10">
				<textarea id="id_content" class="form-control" name="content" rows="10"></textarea>
			</div>
		</div>
		<div class="form-group">
			<div class="col-md-12">
				<input type="button" id="id_submit" class="btn btn-default pull-right" value="Submit">
				<input type="button" id="id_reset" class="btn btn-default pull-right" value="Reset">
			</div>
		</div>
	</form>
</div>
{% endblock problem_content %}